steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/job-reviewer', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/job-reviewer']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'job-reviewer'
      - '--image=gcr.io/$PROJECT_ID/job-reviewer'
      - '--platform=managed'
      - '--region=asia-northeast1'
      - '--allow-unauthenticated'
      - '--port=3000'  # Rails のデフォルトポート
      - '--set-env-vars=RAILS_ENV=production,DATABASE_URL=...（後述）'

images:
  - 'gcr.io/$PROJECT_ID/job-reviewer'
